name: Checks
on:
  pull_request:
    types: [synchronize]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Lint
        run: make lint
      
      - name: Test
        run: make test
